### ISSUE TITLE
Add pause/resume function

### ISSUE THREAD

**Issue by gasipari** [avid21/react-native-timer-countdown#6]
Hello,
Is possible to add a function that pauses the timer and when called again it resume?
Thanks,

**Comment by avid21** [comment]
Hi, @gasipari 
You can pause and resume by using 2 props which are 'onTick', 'initialSecondsRemaining'.
Since you can implement those features from the outside of this component, I think It's good to keep this component as simple as possible. Thank you.

**Comment by gasipari** [comment]
thanks @avid21. Do you have a code sample that would illustrate pause/resume feature using those two props?

**Comment by avid21** [comment]
@gasipari Sorry, I don't have one yet. 

To help you out, I just updated README and described what OnTick function returns. 
For the resume function, you can use the remaining seconds which is returned by OnTick. For the pause function, you can just temporally use text with the remaining seconds instead of this counter.

**Comment by gasipari** [comment]
I got it working! Thanks for your help @avid21

**Comment by avid21** [comment]
@gasipari That's great! If you enjoyed, would you kindly give a star to this repo?

**Comment by gasipari** [comment]
done @avid21

**Comment by avid21** [comment]
@gasipari Thank you.

**Comment by IshaTyagi** [comment]
@noelyoo / @gasipari : Could  you please help me with the functionality of pause and re run.
