### ISSUE TITLE
Is it possible to display only hours and minutes?

### ISSUE THREAD

**Issue by Chatharaju** [avid21/react-native-timer-countdown#8]
Is it possible to display only hours and minutes?

**Comment by avid21** [comment]
Yes, you can use formatSecondsRemaining.

**Comment by lingnaishin** [comment]
how

**Comment by rutsatz** [comment]
If you look in the index.js file, you will see the definition of the function, which is shown below.

`        this.getFormattedTime = (milliseconds) => {
            if (this.props.formatSecondsRemaining) {
                return this.props.formatSecondsRemaining(milliseconds);
            }
            const remainingSec = Math.round(milliseconds / 1000);
            const seconds = parseInt((remainingSec % 60).toString(), 10);
            const minutes = parseInt(((remainingSec / 60) % 60).toString(), 10);
            const hours = parseInt((remainingSec / 3600).toString(), 10);
            const s = seconds < 10 ? '0' + seconds : seconds;
            const m = minutes < 10 ? '0' + minutes : minutes;
            let h = hours < 10 ? '0' + hours : hours;
            h = h === '00' ? '' : h + ':';
            return h + m + ':' + s;
        };`

Then you can create your own because you get the remaining milliseconds and need to return a string.
Below is my function, which displays only seconds.

`    getFormattedTime(milliseconds){
        const remainingSec = Math.round(milliseconds / 1000);
        const seconds = parseInt((remainingSec % 60).toString(), 10);
        const s = seconds < 10 ? '0' + seconds : seconds;
        return s;
    }`

Hugs.

**Comment by noelyoo** [comment]
@rutsatz Thank you for the explanation.
